url: https://agd.data.gouv.fr
name: Blog de l'administrateur général des données
description: Le blog de l'administrateur général des données

lang: fr

github_repository: etalab/agd.data.gouv.fr

include: ["_pages"]

permalink: pretty

exclude:
  - README.md
  - docker-compose.yml
  - circle.yml
  - deploy
  - Gemfile
  - Gemfile.lock
  - vendor
  - .circle
  - node_modules
  - yarn.lock
  - package.json

remote_theme: etalab/template-jekyll
