version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5-stretch

    working_directory: ~/agd.data.gouv.fr

    steps:
      - checkout

      - restore_cache:
          keys:
            - gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-{{ arch }}-{{ .Branch }}
            - gem-cache

      - run:
          name: Ruby dependencies
          command: bundle install --path vendor/bundle

      - save_cache:
          key: gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Build
          command: bundle exec jekyll build --verbose

      - run:
          name: Test
          command: bundle exec jekyll doctor

      - run:
          name: Deploy
          command: ./.circleci/deploy
