#!/bin/bash

echo "Start deploy"
ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -tq root@staticweb-01.etalab.gouv.fr "bash -lc 'cd /var/www/agd.data.gouv.fr && git pull'"
ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -tq root@staticweb-01.etalab.gouv.fr "bash -lc 'cd /var/www/agd.data.gouv.fr && bundle exec jekyll doctor'"
ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -tq root@staticweb-01.etalab.gouv.fr "bash -lc 'cd /var/www/agd.data.gouv.fr && bundle exec jekyll build'"
echo "Deployed Successfully!"

exit 0
